name: 📚 Doc Enhancement
description: Suggest an improvement or addition to existing documentation
title: "[Doc-Enhancement]: "
labels: ["doc-enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an enhancement to our documentation!

  - type: textarea
    id: enhancement-description
    attributes:
      label: Describe the enhancement
      description: A clear and concise description of what you want to improve or add.
      placeholder: "I think it would be better if..."
    validations:
      required: true

  - type: textarea
    id: enhancement-reason
    attributes:
      label: Reason for the enhancement
      description: Explain why this enhancement would be useful.
      placeholder: "This enhancement is important because..."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information like links or screenshots.
      placeholder: "Additional details..."
    validations:
      required: false
